require("plugins")

require("nvim-globals")

require("colorscheme")
require("settings")
require("keys")
require("providers")
require("nvim-bufferline")
require("nvim-explorer")
require("nvim-compe")
require("nvim-telescope")
require("nvim-dashboard")
require("nvim-indentline")
require("nvim-colorizer")
require("nvim-gitsigns")
require("nvim-doge")
require("nvim-dadbod")
require("nvim-mouse-gesture")
require("nvim-zen-mode")
require("nvim-which-key")
require("nvim-template")
require("nvim-lspinstall")
require("nvim-presence")

require("nvim-dap")

require("lsp")
require("lsp.efm-ls")
require("lsp.clangd")
require("lsp.lua-ls")
require("lsp.bash-ls")
require("nvim-dap.js-ts-debug")
require("lsp.js-ts-ls")
require("nvim-dap.python-debug")
require("lsp.python-ls")
require("lsp.json-ls")
require("lsp.yaml-ls")
require("lsp.vim-ls")
require("lsp.css-ls")
require("lsp.docker-ls")
require("lsp.html-ls")
require("lsp.vue-ls")
require("nvim-dap.java-debug")
require("lsp.java-ls")
require("lsp.docker-ls")
require("nvim-dap.c-cpp-rust-debug")
require("lsp.rust-ls")
require("lsp.virtual-text")
require("nvim-dap.nvim-lua-debug")

