require("plugins")

require("nvim-globals")

require("colorscheme")
require("settings")
require("keys")
require("providers")
require("nvim-which-key")
require("nvim-compe")
require("nvim-undotree")

require("nvim-dap")

require("lsp")
require("lsp.efm-server")
require("lsp.c-cpp")
require("lsp.lua")
require("lsp.bash")
require("nvim-dap.js-ts")
require("lsp.js-ts")
require("nvim-dap.python")
require("lsp.python")
require("lsp.json")
require("lsp.yaml")
require("lsp.vim")
require("lsp.css")
require("lsp.docker")
require("lsp.html")
require("lsp.emmet")
require("lsp.tailwindcss")
require("lsp.vue")
require("nvim-dap.java")
require("lsp.java")
require("nvim-dap.c-cpp-rust")
require("lsp.rust")
require("lsp.graphql")
require("lsp.ruby")
require("lsp.virtual-text")
require("nvim-dap.lua")

