require("plugins")

require("nvim-globals")

require("colorscheme")
require("settings")
require("keys")
require("providers")
require("nvim-which-key")
require("nvim-compe")
require("nvim-undotree")

require("nvim-dap")

require("lsp")
require("lsp.efm-ls")
require("lsp.clangd")
require("lsp.lua-ls")
require("lsp.bash-ls")
require("nvim-dap.js-ts-debug")
require("lsp.js-ts-ls")
require("nvim-dap.python-debug")
require("lsp.python-ls")
require("lsp.json-ls")
require("lsp.yaml-ls")
require("lsp.vim-ls")
require("lsp.css-ls")
require("lsp.docker-ls")
require("lsp.html-ls")
require("lsp.emmet-ls")
require("lsp.tailwind-ls")
require("lsp.vue-ls")
require("nvim-dap.java-debug")
require("lsp.java-ls")
require("lsp.docker-ls")
require("nvim-dap.c-cpp-rust-debug")
require("lsp.rust-ls")
require("lsp.virtual-text")
require("nvim-dap.nvim-lua-debug")

