[[plugins]]
repo = "Shougo/dein.vim"

# Design

[[plugins]]
repo = "sainnhe/edge"
hook_add = """
    autocmd VimEnter * nested lua require("colorscheme")
"""

[[plugins]]
repo = "ryanoasis/vim-devicons"

[[plugins]]
repo = "yamatsum/nvim-nonicons"
depends = "nvim-web-devicons"

[[plugins]]
repo = "jbyuki/contextmenu.nvim"

[[plugins]]
repo = "akinsho/nvim-bufferline.lua"
depends = [
    "nvim-nonicons",
    "contextmenu.nvim"
]

[[plugins]]
repo = "glepnir/galaxyline.nvim"
depends = [
    "vim-devicons",
    "nvim-nonicons"
]

# LSP

[[plugins]]
repo = "neovim/nvim-lspconfig"

[[plugins]]
repo = "lspcontainers/lspcontainers.nvim"

[[plugins]]
repo = "kabouzeid/nvim-lspinstall"

[[plugins]]
repo = "nvim-lua/lsp-status.nvim"

[[plugins]]
repo = "RishabhRD/nvim-lsputils"

[[plugins]]
repo = "RRethy/vim-illuminate"

# Testing

[[plugins]]
repo = "vim-test/vim-test"
hook_post_source = """
    let test#strategy = "neomake"
"""

# Debugging (DAP)

[[plugins]]
repo = "mfussenegger/nvim-dap"

[[plugins]]
repo = "theHamsta/nvim-dap-virtual-text"
on_source = "dap"

# Building

[[plugins]]
repo = "neomake/neomake"
hook_post_source = """
    nnoremap <F5> <cmd>NeomakeProject<cr>
"""

# Completions

[[plugins]]
repo = "rafamadriz/friendly-snippets"
on_source = "vim-vsnip"

# Editor

[[plugins]]
repo = "lukas-reineke/indent-blankline.nvim"
hook_post_source = """
    lua require("nvim-indentline")
"""

[[plugins]]
repo = "windwp/nvim-autospace"

[[plugins]]
repo = "andymass/vim-matchup"

[[plugins]]
repo = "machakann/vim-sandwich"

[[plugins]]
repo = "tjdevries/colorbuddy.nvim"

# Highlighting

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
hook_post_update = """
    TSUpdate
    TSUpdate markdown
"""
depends = [
    "ts-rainbow",
    "ts-autotag",
    "treesitter-textsubjects",
    "crazy-node-movement",
    "context-vt"
]

[[plugins]]
repo = "p00f/nvim-ts-rainbow"

[[plugins]]
repo = "windwp/nvim-ts-autotag"

[[plugins]]
repo = "RRethy/nvim-treesitter-textsubjects"

[[plugins]]
repo = "theHamsta/crazy-node-movement"

[[plugins]]
repo = "haringsrob/nvim_context_vt"

# Search

[[plugins]]
repo = "kevinhwang91/nvim-hlslens"

[[plugins]]
repo = "windwp/nvim-spectre"
hook_post_source = """
    lua require("spectre").setup()
"""

[[plugins]]
repo = "nvim-telescope/telescope-media-files.nvim"

[[plugins]]
repo = "nvim-telescope/telescope-fzy-native.nvim"

[[plugins]]
repo = "nvim-telescope/telescope-project.nvim"

[[plugins]]
repo = "nvim-telescope/telescope-dap.nvim"

# Database

[[plugins]]
repo = "tpope/vim-dadbod"

# Spell

[[plugins]]
repo = "lewis6991/spellsitter.nvim"

# Template files

[[plugins]]
repo = "thinca/vim-template"

# Sudo

[[plugins]]
repo = "lambdalisue/suda.vim"
hook_add = """
    lua require("nvim-suda")
"""

# Wakatime

[[plugins]]
repo = "wakatime/vim-wakatime"
if = "luaeval('O.wakatime.enabled')"

# Redmine

[[plugins]]
repo = "toritori0318/vim-redmine"

# Lua

[[plugins]]
repo = "nvim-lua/popup.nvim"

# Python

[[plugins]]
repo = "mfussenegger/nvim-dap-python"

