[[plugins]]
repo = "Shougo/dein.vim"

# Design

[[plugins]]
repo = "sainnhe/edge"

[[plugins]]
repo = "kyazdani42/nvim-web-devicons"

[[plugins]]
repo = "yamatsum/nvim-nonicons"
depends = "web-devicons"

[[plugins]]
repo = "akinsho/nvim-bufferline.lua"
depends = "nonicons"

[[plugins]]
repo = "glepnir/galaxyline.nvim"
depends = "nonicons"

# LSP

[[plugins]]
repo = "neovim/nvim-lspconfig"

[[plugins]]
repo = "lspcontainers/lspcontainers.nvim"
depends = "lspconfig"

[[plugins]]
repo = "kabouzeid/nvim-lspinstall"
depends = "lspconfig"

[[plugins]]
repo = "nvim-lua/lsp-status.nvim"
depends = "lspconfig"

[[plugins]]
repo = "RishabhRD/nvim-lsputils"
depends = "lspconfig"

[[plugins]]
repo = "RRethy/vim-illuminate"
depends = "lspconfig"

# Editor

[[plugins]]
repo = "andymass/vim-matchup"

[[plugins]]
repo = "machakann/vim-sandwich"

# Highlighting

[[plugins]]
repo = "nvim-treesitter/nvim-treesitter"
hook_post_update = """
    TSUpdate
"""
depends = [
    "ts-rainbow",
    "ts-autotag",
    "treesitter-textsubjects",
    "crazy-node-movement",
    "context-vt",
    "nvim-ts-highlightparams",
    "spellsitter"
]
merged = 0

[[plugins]]
repo = "p00f/nvim-ts-rainbow"

[[plugins]]
repo = "windwp/nvim-ts-autotag"

[[plugins]]
repo = "RRethy/nvim-treesitter-textsubjects"

[[plugins]]
repo = "haringsrob/nvim_context_vt"

[[plugins]]
repo = "rohit-px2/nvim-ts-highlightparams"

# Search

[[plugins]]
repo = "kevinhwang91/nvim-hlslens"

[[plugins]]
repo = "windwp/nvim-spectre"
hook_post_source = """
    lua require("spectre").setup()
"""

[[plugins]]
repo = "nvim-telescope/telescope-media-files.nvim"

[[plugins]]
repo = "nvim-telescope/telescope-fzy-native.nvim"

[[plugins]]
repo = "nvim-telescope/telescope-project.nvim"

[[plugins]]
repo = "nvim-telescope/telescope-dap.nvim"

[[plugins]]
repo = "nvim-telescope/telescope-smart-history.nvim"

# Template files

[[plugins]]
repo = "thinca/vim-template"

# Sudo

[[plugins]]
repo = "lambdalisue/suda.vim"
hook_add = """
    lua require("nvim-suda")
"""

# Backup

[[plugins]]
repo = "aiya000/aho-bakaup.vim"
hook_add = """
    let g:bakaup_backup_dir = expand(stdpath("data") . "/backup")
    let g:bakaup_auto_backup = 1
"""

# Wakatime

[[plugins]]
repo = "wakatime/vim-wakatime"
if = "luaeval('O.wakatime.enabled')"

# Redmine

[[plugins]]
repo = "toritori0318/vim-redmine"
if = "luaeval('O.redmine.enabled')"

# Lua

[[plugins]]
repo = "nvim-lua/popup.nvim"

